SetgVar("neovide_cursor_vfx_mode", "pixiedust")
SetgVar("neovide_cursor_vfx_particle_lifetime", 25)
SetgVar("neovide_cursor_vfx_particle_density", 3)
SetgVar("neovide_cursor_vfx_particle_speed", 3)
SetgVar("neovide_cursor_vfx_particle_phase", 5)
SetgVar("neovide_cursor_vfx_particle_curl", 5)
SetgVar("neovide_cursor_trail_length", 0.8)
-- SetgVar('neovide_cursor_antialiasing', false)
SetgVar("neovide_refresh_rate", 60)
SetgVar("neovide_fullscreen", true)
SetgVar("neovide_remember_window_size", true)
-- SetgVar('neovide_cursor_vfx_opacity', 500)
-- SetgVar('neovide_transparency', 0)
-- SetgVar('neovide_floating_blur', 0)
-- SetgVar('neovide_window_floating_opacity', 0)
